In [2]:
import pandas as pd
import numpy as np

In [6]:
df = pd.read_csv("career_path_in_all_field.csv")

In [7]:
df.shape

(9000, 17)

In [8]:
df.head()

,Field,Career,GPA,Extracurricular_Activities,Internships,Projects,Leadership_Positions,Field_Specific_Courses,Research_Experience,Coding_Skills,Communication_Skills,Problem_Solving_Skills,Teamwork_Skills,Analytical_Skills,Presentation_Skills,Networking_Skills,Industry_Certifications
0,Engineering,Urban Planner,3.530439,5,0,2,0,3,1,4,4,2,2,1,0,1,1
1,Chemistry,Art Director,4.018247,1,2,0,0,8,1,3,4,0,3,0,3,0,1
2,Engineering,Chemist,4.636733,1,0,0,0,5,0,1,1,1,2,2,3,4,1
3,Physics,Manager,4.052693,3,1,3,0,1,0,4,1,3,1,2,1,2,0
4,Law,Education Administrator,4.834850,0,2,4,0,0,0,4,4,3,4,4,3,2,0

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9000 entries, 0 to 8999
Data columns (total 17 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Field                       9000 non-null   object
 1   Career                      9000 non-null   object
 2   GPA                         9000 non-null   float64
 3   Extracurricular_Activities  9000 non-null   int64
 4   Internships                 9000 non-null   int64
 5   Projects                    9000 non-null   int64
 6   Leadership_Positions        9000 non-null   int64
 7   Field_Specific_Courses      9000 non-null   int64
 8   Research_Experience         9000 non-null   int64
 9   Coding_Skills               9000 non-null   int64
 10  Communication_Skills        9000 non-null   int64
 11  Problem_Solving_Skills      9000 non-null   int64
 12  Teamwork_Skills             9000 non-null   int64
 13  Analytical_Skills           9000 non-null   int64
 14  Presentation_Skills         9000 non-null   int64
 15  Networking_Skills           9000 non-null   int64
 16  Industry_Certifications     9000 non-null   int64
dtypes: float64(1), int64(14), object(2)
memory usage: 1.2+ MB

In [10]:
df.isnull().sum()

Field                         0
Career                        0
GPA                           0
Extracurricular_Activities    0
Internships                   0
Projects                      0
Leadership_Positions          0
Field_Specific_Courses        0
Research_Experience           0
Coding_Skills                 0
Communication_Skills          0
Problem_Solving_Skills        0
Teamwork_Skills               0
Analytical_Skills             0
Presentation_Skills           0
Networking_Skills             0
Industry_Certifications       0
dtype: int64

In [11]:
df.isnull().sum().sum()

np.int64(0)

In [12]:
df.duplicated().sum()

np.int64(0)

In [13]:
df = df.drop_duplicates()

In [14]:
df.duplicated().sum()

np.int64(0)

In [15]:
df.dtypes

Field                          object
Career                         object
GPA                           float64
Extracurricular_Activities      int64
Internships                     int64
Projects                        int64
Leadership_Positions            int64
Field_Specific_Courses          int64
Research_Experience             int64
Coding_Skills                   int64
Communication_Skills            int64
Problem_Solving_Skills          int64
Teamwork_Skills                 int64
Analytical_Skills               int64
Presentation_Skills             int64
Networking_Skills               int64
Industry_Certifications         int64
dtype: object

In [16]:
numerical_columns = df.select_dtypes(include=['int64', 'float64']).columns
categorical_columns = df.select_dtypes(include=['object']).columns

print("Numerical Columns:")
print(numerical_columns)

print("\nCategorical Columns:")
print(categorical_columns)

Numerical Columns:
Index(['GPA', 'Extracurricular_Activities', 'Internships', 'Projects',
       'Leadership_Positions', 'Field_Specific_Courses', 'Research_Experience',
       'Coding_Skills', 'Communication_Skills', 'Problem_Solving_Skills',
       'Teamwork_Skills', 'Analytical_Skills', 'Presentation_Skills',
       'Networking_Skills', 'Industry_Certifications'],
      dtype='object')

Categorical Columns:
Index(['Field', 'Career'], dtype='object')

In [18]:
for column in categorical_columns:
    print("\n", column)
    print(df[column].unique())

 Field
['Engineering' 'Chemistry' 'Physics' 'Law' 'Marketing' 'Medicine'
 'Computer Science' 'Education' 'Business' 'Architecture' 'Music'
 'Biology' 'Finance' 'Psychology' 'Art']

 Career
['Urban Planner' 'Art Director' 'Chemist' 'Manager'
 'Education Administrator' 'Accountant' 'Cybersecurity Analyst'
 'Special Education Teacher' 'Civil Engineer' 'Artist' 'Architect'
 'Graphic Designer' 'Acoustics Specialist' 'Organic Chemist'
 'Interior Designer' 'Game Developer' 'Music Teacher'
 'Market Research Analyst' 'Conductor' 'Chemical Engineer'
 'School Psychologist' 'Psychologist' 'Surgeon'
 'Digital Marketing Specialist' 'Forensic Psychologist' 'Judge'
 'Analytical Chemist' 'Illustrator' 'Web Developer' 'Art Therapist'
 'Counselor' 'Nurse' 'Marketing Manager' 'Teacher' 'Doctor' 'Paralegal'
 'Data Scientist' 'Software Developer' 'Investment Banker'
 'Curriculum Developer' 'Microbiologist' 'Mechanical Engineer'
 'Biochemist' 'Nuclear Physicist' 'Aerospace Engineer' 'Animator'
 'Sound Engineer' 'Financial Advisor' 'Landscape Architect' 'Ecologist'
 'Legal Analyst' 'Industrial-Organizational Psychologist' 'AI Researcher'
 'Marketing Specialist' 'Risk Analyst' 'Music Therapist' 'Entrepreneur'
 'Physicist' 'Lawyer' 'Inorganic Chemist' 'Brand Manager' 'Actuary'
 'Dentist' 'Biomedical Engineer' 'Legal Secretary' 'Astronomer'
 'Zoologist' 'Legal Consultant' 'Construction Manager' 'Pharmacist'
 'Financial Analyst' 'Principal' 'Fluid Mechanics Engineer'
 'Advertising Manager' 'Biologist' 'Musician' 'Quantum Physicist'
 'Composer' 'Biotechnologist' 'Physical Chemist' 'Electrical Engineer'
 'Architectural Technologist' 'Credit Analyst' 'Physician Assistant'
 'Geneticist' 'Human Resources Specialist' 'Social Media Manager'
 'School Counselor' 'Clinical Psychologist' 'Financial Controller']

In [19]:
df.nunique()

Field                           15
Career                          90
GPA                           9000
Extracurricular_Activities      10
Internships                      3
Projects                         5
Leadership_Positions             2
Field_Specific_Courses          10
Research_Experience              2
Coding_Skills                    5
Communication_Skills             5
Problem_Solving_Skills           5
Teamwork_Skills                  5
Analytical_Skills                5
Presentation_Skills              5
Networking_Skills                5
Industry_Certifications          2
dtype: int64

In [20]:
df.isnull().sum()

Field                         0
Career                        0
GPA                           0
Extracurricular_Activities    0
Internships                   0
Projects                      0
Leadership_Positions          0
Field_Specific_Courses        0
Research_Experience           0
Coding_Skills                 0
Communication_Skills          0
Problem_Solving_Skills        0
Teamwork_Skills               0
Analytical_Skills             0
Presentation_Skills           0
Networking_Skills             0
Industry_Certifications       0
dtype: int64

In [21]:
for column in numerical_columns:
    df[column] = df[column].fillna(df[column].median())

In [22]:
for column in categorical_columns:
    df[column] = df[column].fillna(df[column].mode()[0])

In [23]:
df.isnull().sum()

Field                         0
Career                        0
GPA                           0
Extracurricular_Activities    0
Internships                   0
Projects                      0
Leadership_Positions          0
Field_Specific_Courses        0
Research_Experience           0
Coding_Skills                 0
Communication_Skills          0
Problem_Solving_Skills        0
Teamwork_Skills               0
Analytical_Skills             0
Presentation_Skills           0
Networking_Skills             0
Industry_Certifications       0
dtype: int64

In [24]:
df.shape

(9000, 17)

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9000 entries, 0 to 8999
Data columns (total 17 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Field                       9000 non-null   object
 1   Career                      9000 non-null   object
 2   GPA                         9000 non-null   float64
 3   Extracurricular_Activities  9000 non-null   int64
 4   Internships                 9000 non-null   int64
 5   Projects                    9000 non-null   int64
 6   Leadership_Positions        9000 non-null   int64
 7   Field_Specific_Courses      9000 non-null   int64
 8   Research_Experience         9000 non-null   int64
 9   Coding_Skills               9000 non-null   int64
 10  Communication_Skills        9000 non-null   int64
 11  Problem_Solving_Skills      9000 non-null   int64
 12  Teamwork_Skills             9000 non-null   int64
 13  Analytical_Skills           9000 non-null   int64
 14  Presentation_Skills         9000 non-null   int64
 15  Networking_Skills           9000 non-null   int64
 16  Industry_Certifications     9000 non-null   int64
dtypes: float64(1), int64(14), object(2)
memory usage: 1.2+ MB